[package]
name = "teo"
version = "0.0.1"
edition = "2021"
description = "Backend Framework, Redefined"
license = "MIT"

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
env_logger = "0.9"
log = "0.4"
random-string = "1.0"
jsonwebtoken = "8"
futures = "0.3"
futures-util = "0.3"
actix-http = "3"
regex = "1.5.5"
tokio = { version = "1.18", features = ["macros"] }
async-trait = "0.1.53"
Inflector = "*"
url = "2.2.2"
bcrypt = "0.13"
uuid = { version = "1.1.1", features = ["v4", "fast-rng"] }
cuid = "1.2.0"
mysql_async = { version = "0.30.0", optional = true }
tokio-postgres = { version = "0.7.6", optional = true }
mongodb = { version = "2.2", optional = true }
bson = { version = "2.2", features = ["chrono-0_4", "serde_with"], optional = true }
rust_decimal = "1.24"
rust_decimal_macros = "1.24"
async-recursion = "1.0.0"

[dev-dependencies]
serial_test = "0.7.0"

[features]
data-source-mongodb = ["mongodb", "bson"]
data-source-mysql = ["mysql_async"]
data-source-postgres = ["tokio-postgres"]

[[test]]
name = "test-core"
path = "tests/core/tests.rs"
required-features = ["data-source-mongodb", "data-source-mysql", "data-source-postgres"]

[[test]]
name = "test-mongodb-connector"
path = "tests/connectors/mongodb/tests.rs"
required-features = ["data-source-mongodb"]

[[test]]
name = "test-mysql-connector"
path = "tests/connectors/mysql/tests.rs"
required-features = ["data-source-mysql"]

[[test]]
name = "test-postgres-connector"
path = "tests/connectors/postgres/tests.rs"
required-features = ["data-source-postgres"]
