[package]
name = "teo"
version = "0.0.50"
edition = "2021"
description = "REDEFINED HTTP server framework."
license = "MIT"
build = "build.rs"
homepage = "https://teocloud.io"
documentation = "https://teocloud.io/docs"
repository = "https://github.com/teocloud/teo"

[dependencies]
to-mut = { version = "0.1.0" }
to-mut-proc-macro = { version = "0.1.0" }
actix-web = "4.3.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
chrono = { version = "0.4.23", features = ["serde"] }
env_logger = "0.10.0"
log = "0.4"
random-string = "1.0"
jsonwebtoken = "8.2.0"
futures = "0.3.26"
futures-util = "0.3.26"
actix-http = "3.3.0"
regex = "1.5.5"
tokio = { version = "1.21.0", features = ["macros"] }
async-trait = "0.1.53"
inflector-plus = "0.11.7"
url = "2.2.2"
bcrypt = "0.14.0"
uuid = { version = "1.1.1", features = ["v4", "fast-rng"] }
cuid2 = "0.1.0"
mongodb = { version = "2.3.1", optional = true }
bson = { version = "2.2", features = ["chrono-0_4", "serde_with"], optional = true }
bigdecimal = "0.3.0"
async-recursion = "1.0.0"
colored = "2.0.0"
num-integer = "0.1.45"
pad = "0.1.6"
maplit = "1.0.2"
key-path = "0.1.11"
once_cell = "1.15"
indexmap = "1.9.1"
itertools = "0.10.5"
array_tool = "1.0.3"
pest = "2.5.5"
pest_derive = "2.5.5"
snailquote = "0.3.1"
clap = { version = "4.1.4", features = ["derive"] }
path-absolutize = "3.0.14"
dotenvy = "0.15.6"
toml_edit = "0.19.3"
quaint-forked = { version = "0.1.0", features = [ "all" ] }
whoami = { version = "1.3.0" }
tracing = "0.1"
tracing-subscriber = "0.3"

[dev-dependencies]
serial_test = "1.0.0"

[build-dependencies]
rustc_version = "0.4.0"

[features]
default = ["data-source-mongodb", "data-source-mysql", "data-source-postgres", "data-source-sqlite", "data-source-mssql"]
data-source-mongodb = ["mongodb", "bson"]
data-source-mysql = []
data-source-postgres = []
data-source-sqlite = []
data-source-mssql = []
