[package]
name = "teo"
version = "0.0.33"
edition = "2021"
description = "The next generation HTTP server."
license = "MIT"

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
chrono = { version = "0.4", features = ["serde"] }
env_logger = "0.9"
log = "0.4"
random-string = "1.0"
jsonwebtoken = "8"
futures = "0.3"
futures-util = "0.3"
actix-http = "3"
regex = "1.5.5"
tokio = { version = "1.21.0", features = ["macros"] }
async-trait = "0.1.53"
inflector-plus = "0.11.7"
url = "2.2.2"
bcrypt = "0.13"
uuid = { version = "1.1.1", features = ["v4", "fast-rng"] }
cuid = "1.2.0"
sqlx = { version = "0.6.2", features = ["runtime-tokio-native-tls", "chrono"], optional = true }
mongodb = { version = "2.2", optional = true }
bson = { version = "2.2", features = ["chrono-0_4", "serde_with"], optional = true }
rust_decimal = "1.24"
rust_decimal_macros = "1.24"
async-recursion = "1.0.0"
colored = "2.0.0"
num-integer = "0.1.45"
pad = "0.1.6"
maplit = "1.0.2"
key-path = "0.1.7"
once_cell = "1.15"
indexmap = "1.9.1"

[dev-dependencies]
serial_test = "0.9.0"

[features]
data-source-mongodb = ["mongodb", "bson"]
data-source-mysql = ["sqlx/mysql", "sqlx/any"]
data-source-postgres = ["sqlx/postgres", "sqlx/any"]
data-source-mssql = ["sqlx/mssql", "sqlx/any"]
data-source-sqlite = ["sqlx/sqlite", "sqlx/any"]

[[test]]
name = "test-core"
path = "tests/core/tests.rs"
required-features = ["data-source-mongodb", "data-source-mysql", "data-source-postgres"]

[[test]]
name = "test-mongodb-connector"
path = "tests/integration/connectors/mongodb/tests.rs"
required-features = ["data-source-mongodb"]

[[test]]
name = "test-mysql-connector"
path = "tests/integration/connectors/mysql/tests.rs"
required-features = ["data-source-mysql"]

[[test]]
name = "test-postgres-connector"
path = "tests/integration/connectors/postgres/tests.rs"
required-features = ["data-source-postgres"]
