[package]
name = "teo"
version = "0.0.1"
edition = "2021"
description = "Backend Framework, Redefined"
license = "MIT"

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
mongodb = { version = "2.2", optional = true }
bson = { version = "2.2", features = ["chrono-0_4", "serde_with"] }
chrono = { version = "0.4", features = ["serde"] }
env_logger = "0.9"
log = "0.4"
random-string = "1.0"
jsonwebtoken = "8"
futures = "0.3"
futures-util = "0.3"
actix-http = "3"
regex = "1.5.5"
tokio = "1.18"
async-trait = "0.1.53"
sqlx = { version = "0.5", features = ["mysql", "runtime-tokio-rustls"], optional = true }
sea-query = { version = "^0", features = ["backend-mysql", "backend-postgres", "sqlx-mysql", "sqlx-postgres"], optional = true }
Inflector = "*"

[features]
mongo = ["mongodb"]
mysql = ["sqlx", "sea-query"]
postgres = ["sqlx", "sea-query"]

[[test]]
name = "test-core"
path = "tests/core/mod.rs"
required-features = ["mongo", "mysql", "postgres"]

[[test]]
name = "test-mongodb-connector"
path = "tests/connectors/mongodb/tests.rs"
required-features = ["mongo"]

[[test]]
name = "test-sql-connector"
path = "tests/connectors/sqlx/tests.rs"
required-features = ["mysql", "postgres"]
